apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateways-issuer
spec:  
  selfSigned:
    $patch: delete
  acme:
    email: info@zerotomlops.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: gateways-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: info@zerotomlops.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
