kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  creationTimestamp: null
spec:
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
      creationTimestamp: null
    data: null
  encryptedData:
    api-token: AgDI+3einLosLuuUeU8N+lRp/R2dbzlJeEkERvBlD7YpCNETdDub2VtUuhMXoZwa5DPWrQC09J93H8HQFRyTOiznNvMZVP22MS41iGYmBOM+jD1z+ZTr8Mm2xK60DcDzieupuH5O+yjxOidJCVYtCBKQjlzXHgFDreVr65pQFuHxzr2Q5wohQ7HTCkeL4mejXVxXIZLItE7q0ykNY4R2qUhAb7f3tbshY4IN8HOiHS8W5h4c4+/QNl1uEpKv5usjBdVME5KNjO1tM/9xTyfvOcJWgA93jv/mCo0pmdgTEtaIJp9WPlgFt8eRBbTw1IMROwVHPIS7t04kFJMhwf4GnVoETa4Zl82iJ4rUSx71cN0YaUFrap/OctmNcyAOoyBKjxMiebZTig4ctBNtCLSQAWSqKZKDiDLz57HOQ2R4VjELDrcj+JNrFLM/Enl64/8tSJeZWLRmeyoTnUrykv73ATb7FGTBgR7CUvY1IcXMxxmE9460Qt579p2du6gZHI+a0m3wOh+ULRZM7cJCiOzBMgU2rs6q/kJM7Xlk42OoZUwOX0LALBH8JE10ES8vfSicCMy78flBGAWeKyFFiHXp6pHhl8KNwb5JRFNbKRqRQWcvs80ogaaNfr/w0HZDuR3wyTpyGPLoXgIdE+3yO/pvwfCQ88s8+M4s14OOKbbYRkOqYoR+zyAhSotPnHuAnO7taemRYfh1TM2NU2MWh9DLEgyE7aAlEPIK2jdNBz4GoPOFmWMzyjGRpvYt
