kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  creationTimestamp: null
spec:
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
      creationTimestamp: null
    data: null
  encryptedData:
    api-token: AgC2z7BTOjt2c1x5Zcu90qRFuBbPFYovud7B5MIZ+lz6x+yTzKz9ukOFaHknzqh0HSY25i99C3qOmwPZwGgPEfnadLwg/rQOJ4oiEsBeCgt84YWWGOx5X8rYzBx+X5PVFtJtZrD0h5KTIvekU0CKSMRIj9eabSIbWlMpTLTsIFHh4aVZCsG3MkeRv1vbsv92u3kSLCkyY/qV/Sz4DKLa9YAf5MPhWrvcjeESxKdGXqNUnJB5lfUxLhSjqCCJHkeNPSRE8+7YtSTvp8mGybG0Zxu4HkCd5agK2XWAroiXxiVhHa/CJU4Hj6hBtNjcVyGG3UdJ54o2XRwraBAllWedKtEqxradqQHRcaZUhL5vfN7DgurKdd/qkRA67j/xG3sL+USBV/rCBfUmzhBwjICa+XUA4gt0VQH5pzdPMad+ANmHdfXa3fkM9PjcMCBK5znzP9bjvK8obDn5iTxLziGdmHf+jlGUFp0dJqFOR7k52FrQnbBTxAjKEpTwb4YGCe0bAMzYIqMLC7CPDWOU9rHjpK3J3ehOSGnmGCgTHaB/GkRuUAzcKm5T07BWQinkHDXF7/O+MbbKedf/6o+eRLp7oqtInQ8GEtdrIhsxf8F1XdvwUExZxQSbw3TQ8QMbbrAkhHPH4zQV1dRbUsN08C3Pgwbro5kqavnPWtXgAa13D5SeP/iPbrixevppM0+w2QUOCMvq9TqUFQiw978qpvSaIGbun429wjdy4GclVDVs9hIsZZ047Ar0nriv
