kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: cloudflare-api-token-secret
  namespace: kube-system
  creationTimestamp: null
spec:
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: kube-system
      creationTimestamp: null
    data: null
  encryptedData:
    api-token: AgAiXBaC8jU+0SNmb3/c6CykiGhHtDy+57axblIyC/1Wi2KIIv/aLTJ+YTxRV7J6haZ3VpyMwJ4W4X/RHd0rPMgQlN/rZepLjLmfh1Pk8HcZgDph0SGP/AaE8lt88PGMSNGFGIt2wOtzYXphYSikIIG2AvrQLkoVHrLHjvxw+fjWjzHbauhX7icWHlkEprjmTgRJOB/BM/6ne1DV3nN3EztBOJ+6sNYvlh7SAsgLkHFQd6HxvuOMCkpsAJQatprKfYnlVBbj1lMCeKXxD6fNrTKv8onjmi+HlVGJ01bGAqmGpRUBwstvqmGr7dFgxwuRY46sKb3c7oe1D66Kwqpaap2qgE6GKm/NY+LAgI75fmEVOghTuRkebKcxfIgDl1PcYcWiJNyBFWSrl12Dml/zzKacirlD26sqvQ2kg9wPncNLjw0Wj1aaZ7ew5gPVtzpANjCK72itaJwMNe+DPfnECrZzElxbkfkjtNR1fuy/4x2n7MV8oV6vjdswupRcX88+0FgjtKGwZPio/vzqmU7iQmjHi/6+hU0+nGoBRrsOuE3wJM9/bswLLXrDuEWhFjANxi7x0xBimMlg/ZomiABvBoKhKxnRhm8E8PRffSBJCUJ6NtuiwWnvKr5gzZrHGEVu7xEGtWUH7nGnWnVhGRtwDuMLPqZGi2IYN3BkwMSJjPBcb52/3EXQSpilp3336WJYjDfStruUGQXBtK4994ottDusuwOk7CuQ53wEwNsfrECGCwpNWcBaCOcS
