kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: cloudflare-api-token-secret
  namespace: kube-system
  creationTimestamp: null
spec:
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: kube-system
      creationTimestamp: null
    data: null
  encryptedData:
    api-token: AgBYSNN2tx4dwHoburtwa7vlP+Pd71p/q54UM84TKG3iWHwEOCv/xm50/jk9cB21DiY9K6uEYUjSP5o5mjBRk9qB//GKdS2cgM3qYeEzLwpv60FBhsVT1OlfsF1+yqZ+B3uAGka195duorPqCPFa7D6SMcbJqIQKkNhS5wO3q5zDImSVhP05VA2aHa9ePlBJ0+P15HbMBFBQ9ldhBwKw9Dsxzmu//WpZTWOslNMuPUqt3IcyPvbVWA4klGV2AWhU46OwJjmF9Tdg6vsmB44FnHFkPqXEZLCEzo2KywDXK3+Tlustb8mqV0DsIre/WUNBKN79/J1DovbZXhWnnM49AiTlZBD+9LsuE9jnHp5f2nhyLMhoKvD9dw972s9A+Kte1EY0GANpD06xBbwVaPch3gDSXIsRunX4AlNgx6eBabA6OMIs5tbPshqVDdMAkNjmXfX1EPpX2PQZQP7TtN7ILAruv7gDFAS7iQ9Z7VynISA7Uiv66tpwJ71KHFkOq+Zlf8yuF81ZjIZNzhBP40ceEhF6F3vWqIs30lNEB+NSqYQgXTRN6hkQaFU0H9+autieaht3uMn/SsdAF16kBiDswqjFxJE00FpPygk/21xkP3nUpF3BuqbHAwCT4sTLePwY+lwqC3SBesT9JtD+/bKqYgntFDsDpNSlCxKIX8GhaJpFlPljs+DAFPNEL3WFvYi90kD7nL23T6LA0HoXh6zIEbglSDNCLVlCDZVktrZKqPN/BQRfrVFJ43zt
