kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBE40/CZfvtH9xAaCSvrrG6kgCuoQhrNrSt8l3SMBAXXBt0+Hlca69vD2tl+7+o3nWlhbbe4nGevTyItQm9JW46JrIqnLZTdvJkTh1PQzgZlCVkgfAN0E4KX8+3b9DuKc7mlesqvqMdI8VkLIAql2dggtdeqgw/5CSbrgkU7gwrpPGZOCzZNZ+PtBgfan0whX0RLMitAPqPHb2NYZ2vUaxgjlV39kaMnRsQ/FYtTDSLI8YKaiQKiNrcGmFplQ/0wokQAVOK/byO1DW8pCWAVmN37mk95b+eu/iwegNOVzHzgxkCWzjBgh8AX1IkIdGxGpd6rfaAzVigFLcvMhS71OX328r4x8fLCn9Gt8HwfFQ7VHtkXT5Kgrh17yNJDpcBTEn67xx7HBTSTLent/09iNpBteSh/PqRHpeCNI4zp1ZJXSbEp3pMgz7gT/hZUTZiPzHC4o5dEo+Jd182f6dLNapEP1eaLnaKL7U2FbfGdsvzp7jOMlu/iMnkD8aPPqUkLTwZ6iRp3ssUsBRy6i9vZj/p33EIXMbImd+l5rc0LhlTS8TQFFWNGIFvMqVqalgPhjcessMbDS7I8uoHZmbhLSeiCUBAtaiZSmapyRNl7ISp9nTm01h9Vv95FWwaCZHy88XFkAod1RyHQDmXxMswsTEMEvV5Lt+MPqQsaxCnMFbmXWuRmhCPESHz32Q4ro6huTU3LZkY5w==
    admin-user: AgBqGlfvDJ3IX4jlGaJN0HTtbFXW0MOpMxINaIEzeSCo7rLBtXyiobs31O8DvQkDQwUqhFQg9vDEKGGBgCVzcy+1dcEOqk96YIEWXM8yVwMvpcNNwM4yuRBMqoflBQr2/Gm5IxiVjJg4/8hiNrMos1kfcckctxZKmLVlNYAV2SBpUfuQZJbAnujiwYt/1ONA5QI5rjz0QYgaFzulKMw0IGmLA1KV0Fg5mK/14LAKdAxg6bYOxBSpEbsBUVej+zLv5W1rBETyulYEJNhDg/jbqS+Wy/JqLzRpg82ckNjokua5gFscKYvc/I0gpbdWDIZp8nexEWuJgEs+ATfUYLGd1UaKJHQvd2eg5CeqXRTK7vwIW9ayvyqHcD5yaKPqgNBsrniYOtEiNYi41/RxXxZy7lTlr1Zf67oUWSgxqh5oF70dPyI1v3jftzg7VnRoCeLszJ8pm8AiQQ3afo/nvtHucTjQjyjB6K3u5+cASqOHPExCfwUm8UN4WtUadtdxOVGoRGv8IOzXp7VCd0HRRfZxLu3X1b51Qj8sN08e5z+M1WEBSE/ETtpowxNx4+Ss/ccbWmc8tzLGz+TVZAMj7AMmiAw3yzQ6DLbNl5/46Vz2FsnH71jd1seaAaye0mmq0S2zDXCyqYZ9ySkDXtxBiWBBh4+3JDJQQA28cMaCLFYldB3oaOjP3iLslim2CeEQX5HzIaOoTAv64g==
