kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCaVF0JLvEnM20wkMn6Zyd5KcgrfrRxaZOG3MnNKIfqYYhgQWwakBY2dlURdLB200uqd4zKKLCxETqHJqzC4TTAWNBMjRL6fWHQZG5kWlWslUOn3QoeX9PMjEN3bUEVe2PNke441ogrx1ZaUQTLLDWD7VIHpBCtm7VwLR/0va9DsmJBN3S/JLhDfrK7vNScx/gi8BkRj3wbcH8OtpE8N3PepjidCLGwDQ7cfNZYX7l3Gp/cB5a3/Bc/ywSdk4N+Ikagao/PENiZmAXGcNz9vYitplRX4v0cNobVWPhuvnG1+L5PfRI/jdLvaTI29w+cUwVJK5zeOvKDdlzvWUbPt4nPCPTOoKzvaHi8MaxLZFcdw4mLY8c58N6zkle5bXjUaLzaR2mslHKj2NeRDJaaoIAzmLVTwslJdnriwAS9XkvERzSdNy3Au4QZat2P2pJoOAqjwP9/fSzmhRavH31tz/WlSTpFZvFk+XwDzwjFOARk0PaSgjf8RGOtqRH4ukuWzJIXsXOQ9sWFyjclV2DA8Nc80DR9eYX4EoXE+FXyPLw1249U/2K3mYHKzRqFeh695XAMs8HZH83dkExLiqoG2bluUW5NAPP1sgBOg0pdnLqxW2v+h/ou28kayCU48wl3ntBcXoJQTKIWzSeLBwgwBGC7QA6DJau/7od7+I0Abt5sVeiM6yH5XJP+1Q1onV6sFQw1NMrXDg==
    admin-user: AgB6kQ0rAbIBONFuN4hcZaMchA7NsWYV1FEuYmNNFiXiqwbczzpOAH8mISYImnzRD0ik3w0kzDUYLrhXhzEgFZE3XHpynHIUYv18941ArSIvhJhRi4wwXAC4qF6QVjBRAHLwRv7Nr981hZNm/F93IoEaisRysgs4PSIvifFxJC1mEBR35M5kjY4ge+7+oIP8u8+0Y9CK4pEMwccjw4th4qwsTmWW2b1bGm6e+zX5zF7IRAl8vgcKGErKBU4M7mdEtA+114me75schiZkTtg/0SrMzAhU1uUoeKXUx3k23vLp5UJJYR+eyze0674Nz7g9c/gN/OwWcoOg+TO8Eo9cxuCxQLbxQdmdQAXVdQ5QmqUQxEsj2B77VChndyISnb4grj3aYJg7PB76ZIgAinE0AZS6Y3PGDUZe3ip/lbGo8UUvjaffKvR0VYGiksES912f1OQ0GIgJkJdNd25pECo9mdXDCXlynGtAY6VOIi2e6xupm2hnUt/hmZcBGBBf4NxMNuDaFKwBOlvM2YR19eIucNbfg2jP6LJTR6oaOwCVyXEYDv0Q5F4tArlApFu1Gc3GScFhrEvxMNgWuR8tOVhOf/jMzz6frRyHH7zXFeIiPNyq/3ieLG4fsu6xdGHFFzmIA9/filuJhGipKJq/loejyOfsdqF48n41+AMgO4HjTfjEblQH0t5PXbsrQW6P5ri9Rd8vkXje/Q==
